### ISSUE TITLE
Where to get waf tool?

### ISSUE THREAD

**Issue by chris-blues** [planrich/normalmap#2]
Hi there!

I'm interested in using your normalmap standalone for a script of mine. Unfortunately I don't know what that waf tool is, and where to get it. Searching the web helped me either, so I'm asking here...

Thanks in advance and best regards!
chris

**Comment by brassel** [comment]
I found it here:

https://waf.io/book/#_download_and_installation

**Comment by chris-blues** [comment]
Nice! Thanks!

Maybe someone could add that to the ReadMe?
